# Generated by Django 3.1.5 on 2021-07-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pic',
            field=models.CharField(default='water', max_length=20),
        ),
    ]
